/**
 * P5-1: source_patch artifact builder for candidate extensions.
 *
 * Builds a content-addressed `source_patch` artifact whose blob layout is:
 *   blob[0]: unified diff text (UTF-8)
 *   blob[1]: canonical JSON of the candidate-extension manifest
 *
 * The manifest is validated before building; invalid candidates are rejected
 * before they reach the artifact registry or an isolated runner.
 */

import { createHash } from "node:crypto";
import type { ArtifactRegistry } from "../artifact-registry.ts";
import type { ArtifactManifest } from "../artifact-schema.ts";
import { canonicalJson } from "../canonical.ts";
import type { CandidateExtensionManifest } from "./manifest.ts";
import { validateCandidateManifest } from "./manifest.ts";

export interface SourcePatchArtifactInput {
	candidateManifest: CandidateExtensionManifest;
	diff: string;
	parentIds: string[];
	evidenceRefs: string[];
	scaffoldHash: string;
	modelFingerprint: string;
}

export interface SourcePatchArtifact {
	manifest: ArtifactManifest;
	blobs: Buffer[];
}

export interface StoredSourcePatchArtifact extends SourcePatchArtifact {
	artifactId: string;
}

function sha256Hex(data: Buffer): string {
	return createHash("sha256").update(data).digest("hex");
}

/**
 * Builds a `source_patch` artifact from a validated candidate manifest and a
 * unified diff. Throws if the manifest is invalid or the diff is not a string.
 */
export function buildSourcePatchArtifact(input: SourcePatchArtifactInput): SourcePatchArtifact {
	const validation = validateCandidateManifest(input.candidateManifest);
	if (!validation.ok) {
		throw new Error(`invalid candidate manifest: ${validation.errors.join("; ")}`);
	}
	if (typeof input.diff !== "string") {
		throw new Error("source_patch diff: expected string");
	}

	const diffBlob = Buffer.from(input.diff, "utf8");
	const manifestBlob = Buffer.from(canonicalJson(input.candidateManifest), "utf8");

	const manifest: ArtifactManifest = {
		kind: "source_patch",
		parent_ids: input.parentIds,
		operator: "draft",
		scope: input.candidateManifest.capabilities.slice(),
		evidence_refs: input.evidenceRefs,
		scaffold_hash: input.scaffoldHash,
		model_fingerprint: input.modelFingerprint,
		// Source patches are internal diagnostic artifacts generated by the
		// self-bootstrap pipeline; they carry no free-form user content.
		data_class: "diagnostic_ops",
		retention_policy_ref: "pending_0b",
		blob_hashes: [sha256Hex(diffBlob), sha256Hex(manifestBlob)],
	};

	return { manifest, blobs: [diffBlob, manifestBlob] };
}

/**
 * Builds and stores a source_patch artifact through the artifact registry.
 */
export function storeSourcePatchArtifact(
	registry: ArtifactRegistry,
	input: SourcePatchArtifactInput,
): StoredSourcePatchArtifact {
	const built = buildSourcePatchArtifact(input);
	const artifactId = registry.storeArtifact(built.manifest, built.blobs);
	return { artifactId, manifest: built.manifest, blobs: built.blobs };
}
