// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/cloudflare-ai-gateway.json" with { type: "json" };
import type { Model } from "../types.ts";

export const CLOUDFLARE_AI_GATEWAY_MODELS = values as {
	"claude-fable-5": Model<"anthropic-messages"> & {
		id: "claude-fable-5";
		provider: "cloudflare-ai-gateway";
	};
	"claude-haiku-4.5": Model<"anthropic-messages"> & {
		id: "claude-haiku-4.5";
		provider: "cloudflare-ai-gateway";
	};
	"claude-opus-4.5": Model<"anthropic-messages"> & {
		id: "claude-opus-4.5";
		provider: "cloudflare-ai-gateway";
	};
	"claude-opus-4.6": Model<"anthropic-messages"> & {
		id: "claude-opus-4.6";
		provider: "cloudflare-ai-gateway";
	};
	"claude-opus-4.7": Model<"anthropic-messages"> & {
		id: "claude-opus-4.7";
		provider: "cloudflare-ai-gateway";
	};
	"claude-opus-4.8": Model<"anthropic-messages"> & {
		id: "claude-opus-4.8";
		provider: "cloudflare-ai-gateway";
	};
	"claude-opus-5": Model<"anthropic-messages"> & {
		id: "claude-opus-5";
		provider: "cloudflare-ai-gateway";
	};
	"claude-sonnet-4.5": Model<"anthropic-messages"> & {
		id: "claude-sonnet-4.5";
		provider: "cloudflare-ai-gateway";
	};
	"claude-sonnet-4.6": Model<"anthropic-messages"> & {
		id: "claude-sonnet-4.6";
		provider: "cloudflare-ai-gateway";
	};
	"claude-sonnet-5": Model<"anthropic-messages"> & {
		id: "claude-sonnet-5";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-4.1": Model<"openai-responses"> & {
		id: "gpt-4.1";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-4.1-mini": Model<"openai-responses"> & {
		id: "gpt-4.1-mini";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-4.1-nano": Model<"openai-responses"> & {
		id: "gpt-4.1-nano";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-4o": Model<"openai-responses"> & {
		id: "gpt-4o";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-4o-mini": Model<"openai-responses"> & {
		id: "gpt-4o-mini";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-5": Model<"openai-responses"> & {
		id: "gpt-5";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-5-mini": Model<"openai-responses"> & {
		id: "gpt-5-mini";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-5-nano": Model<"openai-responses"> & {
		id: "gpt-5-nano";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-5.1": Model<"openai-responses"> & {
		id: "gpt-5.1";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-5.4": Model<"openai-responses"> & {
		id: "gpt-5.4";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-5.4-mini": Model<"openai-responses"> & {
		id: "gpt-5.4-mini";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-5.4-nano": Model<"openai-responses"> & {
		id: "gpt-5.4-nano";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-5.4-pro": Model<"openai-responses"> & {
		id: "gpt-5.4-pro";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-5.5": Model<"openai-responses"> & {
		id: "gpt-5.5";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-5.5-pro": Model<"openai-responses"> & {
		id: "gpt-5.5-pro";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-5.6-luna": Model<"openai-responses"> & {
		id: "gpt-5.6-luna";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-5.6-sol": Model<"openai-responses"> & {
		id: "gpt-5.6-sol";
		provider: "cloudflare-ai-gateway";
	};
	"gpt-5.6-terra": Model<"openai-responses"> & {
		id: "gpt-5.6-terra";
		provider: "cloudflare-ai-gateway";
	};
	"o3": Model<"openai-responses"> & {
		id: "o3";
		provider: "cloudflare-ai-gateway";
	};
	"o3-mini": Model<"openai-responses"> & {
		id: "o3-mini";
		provider: "cloudflare-ai-gateway";
	};
	"o4-mini": Model<"openai-responses"> & {
		id: "o4-mini";
		provider: "cloudflare-ai-gateway";
	};
};
